### ISSUE TITLE
Doesnt work with ios  17.1

### ISSUE THREAD

**Issue by alamgira** [wvteijlingen/swiftui-interface-orientation#2]

**Comment by wvteijlingen** [comment]
Thanks for the report! I tested it on iOS 16.4 and that works fine.

Could you provide some more information? 

1. Which exact iOS version are you using?
2. On which device or simulator are you running?
3. Could you provide an example project that shows it not working?

**Comment by alamgira** [comment]
Sorry, i was running ios 17.0.1 in an ipad simulator(10th gen). Unfortunately i cant provide any code sample due to company policy. I am using swiftUI with the latest version of swift. hope that helps

**Comment by wvteijlingen** [comment]
Unfortunately on iPad this package needs some extra configuration. You can solve this in two different ways:

1. Set `UIRequiresFullScreen` to `YES` in the Info.plist
2. Or, make sure that *not all* the orientations are selected in the Deployment Info for the project

**Comment by alamgira** [comment]
Thank you. Adding UIRequiresFullScreen resolved the issue. Thank you for your response
