### ISSUE TITLE
Please Make Version Releases

### ISSUE THREAD

**Issue by yspreen** [wvteijlingen/swiftui-interface-orientation#3]
Just relying on the main branch of a package isn't great for stability or security. Just imagine something like the recent xz issue happens and suddenly main has malicious code. If you're relying on versions you can at least hope that issues get caught before you decide to update to the next one

**Comment by wvteijlingen** [comment]
I've created a version 1.0.0 release, as well as an entry on [swiftpackageindex.com](https://swiftpackageindex.com/wvteijlingen/swiftui-interface-orientation) :)
